enableGlobalCache: false
npmAuthToken: "${NPM_AUTH_TOKEN:-}"

packageExtensions:
  chalk@*:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@*"
      "#supports-color": "npm:supports-color@*"
